[package]
name = "website_checker_student"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
ureq = "2.12"
serde_json = "1.0"

